### ISSUE TITLE
Present quickstart guide images better

### ISSUE THREAD

**Issue by onli** [s9y/s9y.github.io#10]
See https://github.com/s9y/s9y.github.io/commit/5c6e75f2b2fab77bd623a78ce780676266d9262b#commitcomment-15204861. They are a bit big. I don't like just cutting it, but maybe just cutting the thumbnail? Anyone has another idea how those images should be done?

**Comment by yellowled** [comment]
As I said before: either crop the thumbnail or don't use a thumbnail at all (but a text link to the larger image). I think text links to larger images are not a very common pattern, so cropped thumbnails are probably the way to go. Also, this should use MagnificPopup (I can do that later, needs some JS).
