### ISSUE TITLE
Check book

### ISSUE THREAD

**Issue by onli** [s9y/s9y.github.io#13]
There is a TODO in the user documentation to go through the book and a dd what is missing in the docu, see http://docs.s9y.org/docs/users/using/index.html and http://docs.s9y.org/docs/developers/index.html. Let's coordinate here if some or someone wants to do that.

**Comment by yellowled** [comment]
Since the TODOs have been removed, I don't see this as blocking to the website release.

**Comment by onli** [comment]
Since Garvin is completely aware of this, and I doubt that someone else would so this, I'll close here for now.
