### ISSUE TITLE
Blog Design

### ISSUE THREAD

**Issue by onli** [s9y/s9y.github.io#19]
The blog under http://blog.s9y.org/ would need a new theme to work with the new website.

**Comment by yellowled** [comment]
I seem to remember volunteering for this. No idea when I'll find time for it, though.

**Comment by yellowled** [comment]
See [relaunch](https://github.com/s9y/theme_blog/tree/relaunch) branch of s9y/theme_blog. (Not ready to merge yet.)

**Comment by yellowled** [comment]
It's live and it's working. Further improvements should be discussed in https://github.com/s9y/theme_blog.
