### ISSUE TITLE
Forum design

### ISSUE THREAD

**Issue by onli** [s9y/s9y.github.io#20]
The Forum (http://board.s9y.org/) would need a new design as well.

**Comment by onli** [comment]
I pushed a new forum design to https://github.com/s9y/theme_board. Demo: http://onli.columba.uberspace.de/s9y_phpbb/

I worked directly with the css. Possibly annoying in the long run, but since the phpbb style is css anyway it is way easier that way. The result I think is a good starting point, maybe a bit more.

**Comment by yellowled** [comment]
So do you

a. want me to “backport” this CSS to the SCSS in `website_assets` (once it's finished)?
b. want to “backport” this CSS to SCSS yourselves (once it's finished)?
c. want to keep the forum CSS separately?

**Comment by onli** [comment]
I think once we're done this won't change much, and to keep it separated is the easiest way. Option c), if it won't bother you too much.

**Comment by yellowled** [comment]
I disagree with that statement completely, but that's okay. I don't have to be involved in the forum theme.

**Comment by yellowled** [comment]
Silent for two years, also: done. ;-)
