### ISSUE TITLE
Spartacus design

### ISSUE THREAD

**Issue by onli** [s9y/s9y.github.io#21]
And finally there is spartacus that would need a new CSS if it shall work well with the new website (http://spartacus.s9y.org/).

**Comment by yellowled** [comment]
Most interesting question for the time being would be how spartacus even works. Is it possible to "build a test spartacus” (locally)? @garvinhicking?

**Comment by garvinhicking** [comment]
Sure, the emerge\* files in the additional_plugins repo builds that. Should work in most linux machines, maybe also osx. It's less error-prone than addlang.sh I hope ;)

**Comment by yellowled** [comment]
Probably not, it contains some hardcoded paths that expect a certain file/directory structure AFAICS. But I could just work with static HTML here, I guess. It just has 4 views, doesn't it?
- overview/start
- list of plugins
- list of themes
- single theme

**Comment by garvinhicking** [comment]
Yeah, sure, you need to change those paths to your own 
additional_plugins and serendipity installation (it needs a working s9y 
installation to load plugins).

All the static html files it builds are in the "spartacus" subdirectory, 
yes.

**Comment by yellowled** [comment]
See [spartacus-relaunch](https://github.com/s9y/additional_plugins/tree/spartacus-relaunch) branch of s9y/additional_plugins. (Not ready for merge yet.)

If you guys want to see this before #34, you'd have to do a local emerge as described by @garvinhicking above (which I never did) or I could upload the static HTML I used for development.

**Comment by yellowled** [comment]
… and that _should_ be it for Spartacus. As you can see I did not touch the whole XML stuff at all, so at the very least, Spartacus as a service should keep working. LOL.

We should coordinate in Skype or Slack for the relaunch if we want to do site, blog, forum and spartacus all at once, I think, if only to help @garvinhicking out with what to merge with what.

**Comment by yellowled** [comment]
Well, it may not be working properly yet, but it's live.
