### ISSUE TITLE
Structure Contributing section

### ISSUE THREAD

**Issue by onli** [s9y/s9y.github.io#26]
The contributing section on http://docs.s9y.org/docs/contributing/index.html is very important, but also a wall of text. It could get structured anew to highlight all concrete options to help, to make the page easier.

**Comment by yellowled** [comment]
Some random suggestions (open for discussion):
- get rid of the extra hints for German users; if you can read enough English to read this, you can also post in the English forum
- simplify the text; a lot of this was originally written in a “bloomy” copy, it can be shortened _a lot_
- especially shorten the stuff for developers; developers are usually fine with a few lines & links

I _think_ with just these three guidelines, the text could be shortened enough to keep it as a single page. (I could give it a try if nobody is opposed.)

**Comment by yellowled** [comment]
Shortened version: https://gist.github.com/yellowled/ffe943618a28644c7e6658c1e7d746cd

Better? Replace `contributing.md` with this? Anyone?

**Comment by onli** [comment]
Better! It should replace the other.
