### ISSUE TITLE
Automate News section

### ISSUE THREAD

**Issue by onli** [s9y/s9y.github.io#27]
The blog entries feed should get parsed via JS, in doubt use superfeedr to make that possible.

**Comment by garvinhicking** [comment]
jQuery API: https://github.com/jfhovinne/jFeed

**Comment by garvinhicking** [comment]
Committed. @yellowled - can you check if that can be implemented into the build environment you want to use?

Are we set then to make docs.s9y.org our startpage?!

**Comment by yellowled** [comment]
Well, it's not on npm, so we'd have to add it to the repository manually. It can of course still be integrated into the build script. (Not sure I'll find the time to do that over the next week, unfortunately.)

I realize you already spent some time on integrating this, but I would still like to point out that this plugin has not been updated in 5 years. Are we sure we want to use this? [jquery-rss](https://github.com/sdepold/jquery-rss) seems like an alternative that is more actively maintained.

I don't know if that concludes relaunching s9y.org, though.

**Comment by yellowled** [comment]
Okay, done. So if anyone needs to change anything in this plugin or the way it is called here, that now needs to be done in [the website_assets repo](https://github.com/s9y/website_assets/tree/master/site/scripts). Also, a new build must be created there. (I'll see to it that I document the “how” there soonish.)

**Comment by garvinhicking** [comment]
@yellowled just for wrapping this up; jquery-rss relies on external services (feedr) so it is not an alternative, I looked into it.
