### ISSUE TITLE
Add tracking scripts

### ISSUE THREAD

**Issue by yellowled** [s9y/s9y.github.io#33]
The current website incudes tracking scripts for Google Analytics and (as far as I can see) Chartbeat. Not sure if we want to keep those, but if so, the snippets for these need to be added to `_includes/meta-foot.html`.

Thoughts:
- I think it's a good idea to track visitors in general.
- I'd rather include just _one_ tracking script, especially if they don't offer an opt-out. Can we drop Chartbeat?
- We might want to think about using Piwik (which _does_ offer an opt-out) instead, but that would mean we'd have to self-host it. (Can we do that?)

However, these are just my cents. There might be good reasons for using GA and Chartbeat here. Maybe @garvinhicking knows more about it?

**Comment by garvinhicking** [comment]
Cheartbeate is there to track uptime of s9y.org. Since githubs uptime is tracked independently, we don't need it in the future.

I do not want to use a self-hosted stat trackingtool, so I'd like to keep GA. I never really evaluated it, but I suppose if anyone wants to, either Jannis or me should be able to hand out GA access for that...

**Comment by yellowled** [comment]
Yeah, I figured self-hosted would not be feasible, just wanted to point out the option.

I guess we could seize the opportunity to update the GA snippet to the latest snippet format?

```
<!-- Google Analytics: change UA-XXXXX-Y to be your site's ID. -->
<script>
    window.ga=function(){ga.q.push(arguments)};ga.q=[];ga.l=+new Date;
    ga('create','UA-XXXXX-Y','auto');ga('send','pageview')
</script>
<script src="https://www.google-analytics.com/analytics.js" async defer></script>
```

The site ID is `UA-77038-1`. I don't think we should add the code before actually switching to the GitHub version of the site in order to not pollute the data?

**Comment by garvinhicking** [comment]
I think it wouldn't terribly hurt, better to do it now and not forget about it?! :)

**Comment by yellowled** [comment]
Done. Closing this.

Also added issues to add the same code to the board and blog theme later. Same for Spartacus, but we don't have a repo for that. I guess we'll just have to remember that one.
