### ISSUE TITLE
Consider a breadcrumb nav

### ISSUE THREAD

**Issue by yellowled** [s9y/s9y.github.io#38]
As @th-h suggested in #36, a breadcrumb navigation might support orientation within the site, especially the docs. Not sure if that's possible in Jekyll, though. It should be generated automagically/on generation of the site, not hard-coded.

**Comment by yellowled** [comment]
We have to remember that GitHub Pages does not allow to use Jekyll plugins, so it looks like https://github.com/comsysto/jekyll-breadcrumb-for-github-pages/ is our only option.

**Comment by th-h** [comment]
Looks good for me.

I can have a closer look and submit a PR, if you'd like, but not before 2016-10-17, I fear.

**Comment by yellowled** [comment]
@th-h Did you mean 2017-10-16? ;)

**Comment by th-h** [comment]
That was ... not so easy.

https://github.com/comsysto/jekyll-breadcrumb-for-github-pages/ does not work with our structure; it requires that all pages are named "index.html". Furthermore it loops over all pages to find the right one and get its title instead of picking the correct page from the site.pages array.

So I rewrote the function, mostly by trial and error. It should work now.

This is the non-minified version:
```
<ol class="breadcrumb">
  <li><a href="{{ site.baseurl }}/">Start</a></li>
  {% capture page_url_without_index_html %}{{ page.url | remove: "/index.html" }}{% endcapture %}
  {% assign splitted_url_parts = page_url_without_index_html | split: '/' %}
  {% capture forLoopMaxInt %}{{ splitted_url_parts.size | minus:1 }}{% endcapture %}
  {% assign j = forLoopMaxInt | plus: 0 %}
  {% for i in (1..forLoopMaxInt) %}
    {% if splitted_url_parts[i] contains ".html" %}
      {% capture current_breadcrumb_url %}{{next_prepender}}/{{ splitted_url_parts[i] }}{% endcapture %}
    {% else %}
      {% capture current_breadcrumb_url %}{{next_prepender}}/{{ splitted_url_parts[i] }}/{% endcapture %}
    {% endif %}
    {% capture next_prepender %}{{next_prepender}}/{{ splitted_url_parts[i] }}{% endcapture %}
    {% assign matched_page = site.pages | where:"url",current_breadcrumb_url %}
    <li{% if i == j %} class="active"{% endif %}>
    {% if i == j %}
      {{matched_page[0].title}}
    {% else %}
      {% capture breadcrumb_page_page_url_without_index_html %}{{ matched_page[0].url | remove: "index.html" }}{% endcapture %}
      <a href="{{ site.baseurl }}{{breadcrumb_page_page_url_without_index_html}}">{{matched_page[0].title}}</a>
    {% endif %}
    </li>
  {% endfor %}
</ol>
```
