### ISSUE TITLE
Clean up spartacus website

### ISSUE THREAD

**Issue by yellowled** [s9y/s9y.github.io#39]
~~Add class `theme-single` to `<div class="theme">` on pages where single theme is displayed~~
- [x] Remove or move unused image assets in `homepage/css`
- [x] Remove old CSS files

**Comment by yellowled** [comment]
Does anyone know if `homepage/header.png` is actually _used_ anywhere? It does not look like it, I don't recall ever seeing it anywhere …

**Comment by onli** [comment]
You mean https://github.com/s9y/additional_plugins/blob/master/homepage/header.png? It looks useable to me, but I don't remember having it seen anywhere yet.

**Comment by yellowled** [comment]
Yeah, and the thing is, we even have PSDs of it. I don't see where we would use it _now_, but I also do not recall this ever being used anywhere. It might be a draft or something.

**Comment by yellowled** [comment]
I moved the PSD files to `source`, but I doubt they will ever be used for anything.

**Comment by yellowled** [comment]
We can skip the `theme-single` class, it just removes a margin that is not required in single theme view. Probably not even worth the hassle of trying to implement it. (It does not hurt the display at all.)
