### ISSUE TITLE
When on spartacus (plugins or themes) the link to the doc section is broken

### ISSUE THREAD

**Issue by mariohommel** [s9y/s9y.github.io#41]
The link should point to http://docs.s9y.org/docs/index.html but when you're on the spartacus sites the link points to http://s9y.org/docs/.

**Comment by mariohommel** [comment]
The link should point to http://docs.s9y.org/docs/index.html but when you're on the spartacus sites the link points to http://s9y.org/docs/.

**Comment by yellowled** [comment]
That is interesting, because http://s9y.org/docs/ should redirect to that page … but fix committed, very good catch!
