### ISSUE TITLE
Spartacus site 404s

### ISSUE THREAD

**Issue by yellowled** [s9y/s9y.github.io#42]
Created issue to document things already mentioned in Slack. The [Spartacus site](http://spartacus.s9y.org) throws 404 errors on some assets.
- `scripts/modernizr/modernizr.js`
- `scripts/master.js`
- `img/logos/*.png`

I suspect there is some sort of rewriting in place that does not cover these assets(?) since they are in new directories created by me in the Spartacus relaunch.

For instance, `http://spartacus.s9y.org/scripts/master.js` is  _actually_ `http://spartacus.s9y.org/homepage/scripts/master.js`, but the `/homepage/` part of the path is not being rewritten properly for any of the files listed above.

**Comment by garvinhicking** [comment]
@yellowled Actually there should not be any rewriting, as it's not possible properly on the SourceForge webserver where the spartacus.s9y.org is located. http://spartacus.s9y.org/scripts/master.js is not the proper URL, but http://spartacus.s9y.org/homepage/scripts/master.js is, so you need to use the /homepage/ prefix for everything. 

Only the index.php file is copied to the main directory too, I think. All other links should need the homepage/ prefix there...

**Comment by yellowled** [comment]
@garvinhicking I can of course do that, but why does it work for the CSS? http://spartacus.s9y.org/css/master.css works, although that should be http://spartacus.s9y.org/homepage/css/master.css as well? Meaning I can reference the CSS _wihtout_ the prefix but not the JS?

**Comment by yellowled** [comment]
So, I just changed all path to external assets to include `homepage`. If that works as intended after Spartacus autopulls, this can be closed. If the logos still don't work, I need to change the path again in (S)CSS. 🙄 

But none of this (I think) should interfere with the SSL things because the URLs to external assets still don't have a protocol.

**Comment by garvinhicking** [comment]
Because the 'css' directory is also copied I guess. I don't know where 
and how, though. Might be a complex cronjob at some point, the uberspace 
host only syncs the homepage/ subdirectory.

The best way would be to reference all the assets through homepage/...

**Comment by yellowled** [comment]
> The best way would be to reference all the assets through homepage/...

That's what https://github.com/s9y/website_assets/commit/cbd6978a252cea0503206e430a85fc5e04ad6927 and https://github.com/s9y/additional_plugins/commit/f2640a58eccc301400413be96e51d4e3b4e28396 should do. It might just be that the logos still don't work properly, then I'll have to revert the path change in the CSS and we'll have to wait for another autopull. (Doesn't really matter anymore at this point.)

**Comment by yellowled** [comment]
> It might just be that the logos still don't work properly, then I'll have to revert the path change in the CSS and we'll have to wait for another autopull.

Which is exactly what happened. Should be fine by midnight.
