### ISSUE TITLE
Theme list sorting

### ISSUE THREAD

**Issue by yellowled** [s9y/s9y.github.io#45]
The [list of all themes](http://spartacus.s9y.org/index.php?mode=template_all) as well as the theme list in the sidebar on Spartacus are supposed to be sorted alphabetically (I think), but the sorting is case-sensitive (meaning first A, then Z, then a, then z).

“True” alphabetic sorting would be nicer.

Also, quoting [@bauigel](https://github.com/s9y/Serendipity/issues/475):

> Within S9y there is a "featured themes" section where users can see up-to-date templates. This section is missing on spartacus.s9y.org and users only see themes alphabetically with a lot of old themes. We should include this featured area there too.

**Comment by th-h** [comment]
The "featured themes" thing has been done in #76.

**Comment by th-h** [comment]
Theme list "true” alphabetic sorting done.
