### ISSUE TITLE
OpenGraph

### ISSUE THREAD

**Issue by yellowled** [s9y/s9y.github.io#46]
As of now, if https://s9y.org is shared on Facebook, the Open Graph image is picked (randomly, I think) from one of the images on the page. `<title>` is used for the OG title, the description meta element for the OG description. We can and should optimize this.

Proposed markup:

```
<meta property="og:title" content="{{ page.title }}">
<meta property="og:site_name" content="{{ site.title }}">
<meta property="og:description" content="{{ site.description }}">
<meta property="og:image" content="…">
<meta property="og:url" content="{{ site.url}}{{ page.url | replace:'index.html',''}}">
<meta name="twitter:card" content="…">
```
“…” would be the Open Graph image – at least 600x315, 1200x630 or larger is preferred. The s9y flower PSD is close to 600x315, so I think that would be a good option. Same for twitter:card.

**Comment by yellowled** [comment]
Open Graph img is at https://docs.s9y.org/img/s9y-opengraph.jpg

**Comment by yellowled** [comment]
Hmmm. This makes https://docs.s9y.org the canonical URL as well as the og:url – I think that's okay since https://s9y.org only redirects there anyway, but it *might* be better to set this to https://s9y.org for SEO reasons. Not sure.

@onli @garvinhicking @donchambers any preferences/ideas on this?

**Comment by yellowled** [comment]
(Leaving this open until the canonical URL is discussed.)

**Comment by onli** [comment]
Probably does not matter too much. I'd prefer https://s9y.org to further support later moving away from https://docs.s9y.org, but since then that url would become the redirect…

**Comment by garvinhicking** [comment]
Hm not sure if a canonical url that is a redirect is proper. Better leave it at doca.s9y.org and we change it if we do that in the future; docs.s9y.org will then redirect so all would be fine?!

**Comment by yellowled** [comment]
Leave it as it is seems to be the consensus for the time being. :)
