### ISSUE TITLE
Sponsor link to "Regionalportal"  not working

### ISSUE THREAD

**Issue by th-h** [s9y/s9y.github.io#49]
All doc pages show a link to www.cityreview.de - which currently does not have a working webserver running.

I did not want to remove the link, as I don't know whether they're still sponsoring s9y or if there is another site we could linkt to.

**Comment by th-h** [comment]
Do we still use servers or bandwidth from Regionalportal?

**Comment by onli** [comment]
Not that I know of. And even if, no gain for them in linking a dead site. That should be removed.
