### ISSUE TITLE
New docs start page

### ISSUE THREAD

**Issue by yellowled** [s9y/s9y.github.io#5]
The [start page](http://docs.s9y.org/docs/index.html) for the docs ([docs/index.md](https://github.com/s9y/s9y.github.io/blob/master/docs/index.md)) does not work in the new site at all. Needs to be rewritten, maybe even “repurposed”.

**Comment by onli** [comment]
Good enough?

**Comment by yellowled** [comment]
I assume that most of this will be work in progress until we actually launch this, so yes. ;)
