### ISSUE TITLE
Orphaned files

### ISSUE THREAD

**Issue by th-h** [s9y/s9y.github.io#52]
AFAIS there are no links to these files:
```
/docs/faq/performancing-setup.md
/docs/faq/popfetcher-posting-entries-by-email.md
/docs/faq/windows-live-writer-setup.md
```

**Comment by yellowled** [comment]
AFAICS, those would need to be added to the [FAQ](https://docs.s9y.org/docs/faq/index.html), but there's no proper section for them (yet) and they are not important enough to justify their own section.

**Comment by th-h** [comment]
Yep. I just thought we should document it somewhere to keep track of those files.

**Comment by yellowled** [comment]
I think [Blog editors/interfaces](https://docs.s9y.org/docs/faq/index.html#docs-blog-editorsinterfaces) is close enough to a common denominator for these three, and there might be even more to add to it.
