### ISSUE TITLE
rel="canonical" uses "http" instead of "https"

### ISSUE THREAD

**Issue by th-h** [s9y/s9y.github.io#54]
Each page includes a `<link rel="canonical" href="$URL">` element in its header, created by the following code in `_includes/meta-head.html`:
```
    <link rel="canonical" href="{{ site.url }}{{ page.url | replace:'index.html',''}}">
```

`site.url` obviously is `http://docs.s9y.org/`, but shoulld be `https://docs.s9y.org/`.

Perhaps one could use a `replace` as it is done for `index.html`?

**Comment by yellowled** [comment]
I think we can just set `site.url` in `_config.yml`. Will look into that.

**Comment by th-h** [comment]
Works like a charm. Thanks!
