### ISSUE TITLE
Code primer: order list of variables (alphabetically)

### ISSUE THREAD

**Issue by th-h** [s9y/s9y.github.io#58]
https://docs.s9y.org/docs/developers/code-primer.html contains quite some list of variables which are - as far as I can see - not sorted in any obvious way.

I suggest to sort them alphabetically and would be willing to do that, if we agree on this.

**Comment by th-h** [comment]
With some more coffee, the lists seem to be ordered - mostly - by the order of appearance in the config files - which makes a lot of sense. Perhaps we should leave it that way.

**Comment by yellowled** [comment]
Make it so. :-)
