### ISSUE TITLE
Create quickstart quide

### ISSUE THREAD

**Issue by yellowled** [s9y/s9y.github.io#6]
Currently, [quickstart](http://docs.s9y.org/docs/quickstart/index.html) ([docs/quickstart/index.md](https://github.com/s9y/s9y.github.io/blob/master/docs/quickstart/index.md)) ist just a placeholder. It is supposed to contain an (illustrated?) “X easy steps to your own self-hosted s9y installation” because Supersized is not a thing anymore.

**Comment by yellowled** [comment]
If I remember correctly, @onli volunteered for this?

**Comment by onli** [comment]
:+1:

**Comment by onli** [comment]
See https://github.com/s9y/s9y.github.io/commit/5c6e75f2b2fab77bd623a78ce780676266d9262b

**Comment by onli** [comment]
Any further feedback? Can it stay like that till user feedback arrives (=shall we close here)?

**Comment by yellowled** [comment]
We could probably just open a new issue for the [screenshots](https://github.com/s9y/s9y.github.io/commit/5c6e75f2b2fab77bd623a78ce780676266d9262b#commitcomment-15204861) and close this.

**Comment by onli** [comment]
Done in https://github.com/s9y/s9y.github.io/issues/10
