### ISSUE TITLE
Broken feed parser

### ISSUE THREAD

**Issue by yellowled** [s9y/s9y.github.io#64]
https://docs.s9y.org uses [jFeed](https://github.com/jfhovinne/jFeed) to extract information from the blog's RSS feed and inject it into the page. For whatever reason, that doesn't work any more for the content (headings are still parsed correctly).

Since jFeed hasn't changed in over 6 years and hasn't been updated or changed – did we change something in RSS feeds in s9y?

**Comment by th-h** [comment]
Switching the feed from RSS to atom works. (Better not touch anything else ...)
