### ISSUE TITLE
Deprecate sourceforge.net

### ISSUE THREAD

**Issue by th-h** [s9y/s9y.github.io#68]
It's not strictly an issue with s9y.github.io, but I think we should track it somewhere ...

https://sourceforge.net/projects/php-blog/ should be deprecated - the summary replaced by a notice that development is now done here at Github and releases are solely published here.

Perhaps the screenshots should be removed, too.

**Comment by onli** [comment]
Currently there is a note: 

 > Development has moved to GitHub: https://github.com/s9y/Serendipity!

That's probably okay like that, no?

**Comment by th-h** [comment]
Yeah, works for me. Thanks!
