### ISSUE TITLE
Split up FAQ

### ISSUE THREAD

**Issue by yellowled** [s9y/s9y.github.io#7]
As of now, the [FAQ](http://docs.s9y.org/docs/faq/index.html) main page would be pretty long. Since the FAQs are grouped anyway, we could split up the one FAQ file ([docs/faq/index.md](https://github.com/s9y/s9y.github.io/blob/master/docs/faq/index.md)) in subsections.

Up for discussion.

**Comment by yellowled** [comment]
@garvinhicking @onli @mariohommel @donchambers Thoughts? :)

**Comment by mariohommel** [comment]
I think splitting it would give us a better overview to keep the FAQ up to date.

**Comment by onli** [comment]
I'm okay with splitting it technically, but think that a FAQ in the end should be a single page. Otherwise questions can't be found easily. So, if we split it we should combine it later with iframes or something.

I'll go through the questions and see (again?) what is still current, maybe the next step would be to rework the presentation (YL, you mentioned a jquery plugin?) to see how long it really is.

**Comment by yellowled** [comment]
- I disagree with the single page, simply because of the sheer number of questons and answers. Some of the answers are quite extensive.
- I am also very much opposed to using `iframe`s for everything that we can't figure out in Jekyll at first glance.
- If it is hard to find questions in split pages, then in my opinion the categories for the FAQ just aren't good enough. What we could do is make an overview which contains just (all) the questions (to keep it short).
- We should also double-check if the questions are **really** _frequently_ asked.
- Yes, there is a jQuery plugin to make the answers collapsible, but that is flexible enough to handle almost any markup. Shouldn't have to be considered at this point.

**Comment by garvinhicking** [comment]
What about the "accordion"-style idea? We could present all FAQ items, and even some short answers. Longer answers could be linked to dedicated pages. It would of course mean for those longer answers to need to edit two files (the central one and the dedicated one), but that should be workable.

**Comment by yellowled** [comment]
> What about the "accordion"-style idea?

That is what the jQuery plugin does.

> Longer answers could be linked to dedicated pages.

I don't see a feasible way to write that in Markdown.

**Comment by garvinhicking** [comment]
Wouldn't that just be something like:

---

## You can do blabla, read more ((faq/specific-item.md)(here)).

(I don't remember the markdown syntax for linking right now, you get the gist)

**Comment by yellowled** [comment]
Sure, but that would be hidden in the collapsible part of the accordion first.

My concern is that the FAQ will get harder to maintain if we keep it in one file, even if we roll out the long answers to seperate pages. Then again, I don't see the issue with splitting them up if the questions are categorized properly.

**Comment by garvinhicking** [comment]
I would be fine with having it like
- SECTIONTITLE
  Accordionstart
  Q1
  Q2
  Q3
  Accordionend
- SECTIONTITLE "
  Accordionstart
  Q1
  Q2
  Q3
  Accordionend

We could even think about using two stacked accordions within each other, but I don't like this and would prefer scrolling.

**Comment by yellowled** [comment]
At the end of the day, the important question is: is this possible in Markdown and is the resulting Markdown maintainable without pulling your hair out. `¯\_(ツ)_/¯`

We _might_ need some additional JS or Markup here because the actual markup structure is a bit different than what you outlined:

```
SECTIONTITLE (h3)
Q1 (h4)
A1
Q2 (h4)
A2
…
```

The problem is that A1 could be a `<p>`, while A2 could be an `<ul>`. Or a `<p>` followed by an `ol`. Or whatever. So we might need to wrap the answers in `div`s or something for the accordion script to work.

However, all this would also be possible in a split FAQ. Of course, we can always split the FAQ later, if and when it really _does_ get too large for one page.

**Comment by onli** [comment]
> if and when it really does get too large for one page.

I'd prefer that. I don't think it is too long currently.

>  Longer answers could be linked to dedicated pages. 

We should do that more. A FAQ is no docu and to point to the exact right documentation is a good answer. I actually removed one or two links to the documentation, where the target page seemed gone to me. But the short answer was good enough.
