### ISSUE TITLE
"Ask the expert" section

### ISSUE THREAD

**Issue by yellowled** [s9y/s9y.github.io#8]
One could argue that [Ask the expert](http://docs.s9y.org/docs/faq/ask-the-expert/index.html) is pointless. It feels as if these questions should be part of the FAQ, especially if the FAQ was split up (see #7).

**Comment by garvinhicking** [comment]
Yes, definitely, the plan should be to migrate all of this into a FAQ, best split up into portions.

Or maybe we could leave it as a large site and add an accordion for the headers? Sorry for mixing up issues.

**Comment by yellowled** [comment]
> Or maybe we could leave it as a large site and add an accordion for the headers?

We can still do that with the FAQ split up in sections. The question is, do we want to split it up, and should the questions from “Ask the experts” be migrated to the resulting FAQ subsections?

**Comment by mariohommel** [comment]
@yellowled is right, most of the documents in "Ask the expert" sound like FAQs. Maybe there is even double content. We should migrate these documents to the FAQ.

**Comment by onli** [comment]
Who will do that? @mariohommel, is it your baby?

**Comment by mariohommel** [comment]
I can do it, but I think I should wait, until we know how the FAQ will be structured.

**Comment by onli** [comment]
Read that discussion as pretty much done, that it will stay one page for now. If you integrate it soon and it has to be restructured later because I was wrong, I'd volunteer ;)

**Comment by mariohommel** [comment]
OK. :)

**Comment by onli** [comment]
I had a closer look at it.

It seems to me like there are no (which did I miss?) questions in there that do belong in the FAQ and are not already covered. However, the section includes several useful explanations, like how to setup wblogger, that I do not see covered elsewhere. I will try to integrate them in the normal user documentation. 

But it is hard to do that without having a real overview of what is in there, meaning 1) sorry if something gets misplaced 2) I'd still appreciate help with that :)

It'd be great if we could get the site up and running with the new release, maybe even the beta. There is not that much missing…

**Comment by onli** [comment]
To not forget this: What I was not able to integrate is https://github.com/s9y/s9y.github.io/blob/8fdd5465e154272562ea45e30b1bbeee2ae5f7e9/docs/faq/ask-the-expert/moving-to-new-directory.md. It is unfinished, missing the images, and the link to the script is down. I don't want to copy it into the docs like this, as I won't be able to finish it.

**Comment by yellowled** [comment]
I do not want to decide this, but given the state of said page, I propose to remove it from the docs altogether. It doesn't make sense to keep broken documentation around.
