### ISSUE TITLE
Hosting providers

### ISSUE THREAD

**Issue by yellowled** [s9y/s9y.github.io#9]
As far as I have looked (not even 25%), the list of [hosting providers](http://docs.s9y.org/docs/users/hosting.html) is _horribly_ outdated.

Aefer and Supersized don't even exist anymore. As far as I understand it, there has not been an official Debian package since s9y 1.5.3. I assume (without having checked) that a lot of the links to hosters are 404s now since hosters change their plans and web sites all the friggin' time.

I would suggest to go “quality over quantity” here instead. List only a few hosting providers, but list those that have actually proven to work well. Do not link to specific plans, those **will** change.

**Comment by yellowled** [comment]
Also, don't list Linux distro packages any longer. Linux admins will find them through their package managers anyway.

**Comment by onli** [comment]
Did a first rework in https://github.com/s9y/s9y.github.io/commit/1f3516edf880c64f899d0099b65577a8b8679d22

**Comment by onli** [comment]
Shall we leave it like that, or are there improvement proposals?

**Comment by yellowled** [comment]
It's a tad scarce now, isn't it? ;)

I think the issue is done, but we would probably want to list more providers over time. However, we would need to discuss what makes a hoster "suitable". For instance, all-inkl is okay for s9y hosting in general, but their permissions system can make using Spartacus kind of awkward. Yet they're still way better than other hosters, and it really depends on how one uses Spartacus (i.e. if you change plugins manually).

I still find it odd that commercial support and hosting providers are on the same page, by the way.

**Comment by onli** [comment]
Agreed, it should be a bit more. Don't know if  all-inkl is a good example, is spartacus working fine if you only use spartacus?

The commercial support should be on another page if the company is not primarily offering hosting (@garvinhicking ?). It could go to the docs overview page, or maybe we add a page _Support_ mentioning this and the forum?

**Comment by yellowled** [comment]
> is spartacus working fine if you only use spartacus?

I don't know, it's the reason why I moved to Uberspace. I guess it's subjective, though. I was just tired of dealing with it.
