### ISSUE TITLE
Update minimum required php version from "7.0" to "7.3" for version 2.4.0/2.4.1 and announce switch to PHP 8.0 very soon

### ISSUE THREAD

**Issue by stevleibelt** [s9y/s9y.github.io#90]
Because of [this](https://github.com/s9y/Serendipity/issues/794) issue ticket. We need to update the "minimum required PHP version" from >>7.0<< to >>7.3<< for serendipity version "2.4.0" and "2.4.1".

Further more, announce upcoming switch to PHP 8.0 as "very soon".

### 20221122

* Changed target version from 8.0 to 7.3 because of @surrim [comment](https://github.com/s9y/s9y.github.io/issues/90#issuecomment-1322548817)

**Comment by fe-hicking** [comment]
IMP we should still support PHP 7.4. use polyfills in compat.inc for unsupported functions.

Raising the bar without a real need is IMO not ideal especially for long term users. Many LTS distros still support PHP 7.4 on their own...

**Comment by fe-hicking** [comment]
(Array_key_first would be supported by PHP 7.3 even, what else would require PHP 8?)

**Comment by onli** [comment]
Yeah, that's impossible. We need to have transition versions, otherwise it would be not possible to update from PHP 7 to PHP 8. Serendipity 2.4 definitely supports 7.4 and probably 7.3, so I'd go with 7.3 as new minimum version. @surrim, you agree?

**Comment by stevleibelt** [comment]
I am fine to adapt my initial issue description once we've settled the minimum php version.

**Comment by surrim** [comment]
> ... so I'd go with 7.3 as new minimum version. @surrim, you agree?

@stevleibelt I would prefer to set the needed PHP version to 7.3 for the 2.4.0/2.4.1 release and announce that we are going to switch to PHP 8.0 very soon - and make a transition version which runs with both, PHP 7.3 and 8.0.
After that I see no reason to restrict new code to an unsupported PHP version anymore. I think webhosters have to switch to PHP 8.x anyway.

Here is an incomplete list of used PHP versions:

Debian 10 LTS (Buster): PHP 7.3  
Debian 11 (Bullseye): PHP 7.4  
Debian 12 (Bookworm): PHP 8.1

Fedora 35: PHP 8.0  
Fedora 36: PHP 8.1  
Fedora 37: PHP 8.1

Ubuntu 18.04 LTS (Bionic): PHP 7.2  
Ubuntu 20.04 LTS (Focal): PHP 7.4  
Ubuntu 21.10 (Impish): PHP 8.0  
Ubuntu 22.04 LTS (Jammy): PHP 8.1

**Comment by onli** [comment]
We have to be a bit careful with PHP 8. exactly because of the list you show. My very own blog for example runs under Ubuntu 20.04, an upgrade would be not possible currently if we made 8.0 a requirement.

But for now PHP 7.3 seems like the best solution (ideal would have been to notice the incompatibility earlier and enable 7.0 support, but it was a long development cycle and PHP 8.0 was more important, so I won't be too angry with myself ;) ) .

@surrim, could you update https://github.com/s9y/s9y.github.io/pull/91 so we can merge this?

**Comment by surrim** [comment]
> @surrim, could you update #91 so we can merge this?

Done :)
I had to create a different pull request, because I can't switch the branch(name) once I published the request.. and I try to avoid confusing branch names 🚀 
See https://github.com/s9y/s9y.github.io/pull/92

**Comment by onli** [comment]
Docs are fine now in this regard, or is something missing?

**Comment by surrim** [comment]
> Docs are fine now in this regard, or is something missing?

The only missing thing is a schedule for the next releases and their PHP support. But that's something for a new issue :wink:

**Comment by onli** [comment]
Well, open the issue and let's make a plan :)

**Comment by stevleibelt** [comment]
Thanks for the discussion and the work.

**Comment by onli** [comment]
> The only missing thing is a schedule for the next releases and their PHP support.

To follow up on that: https://board.s9y.org/viewtopic.php?t=25714. Please chime in, both of you :) 

(Making github issues out of that is the idea)
