### ISSUE TITLE
Sentence about bytecode compilers contains obsolete and possibly incorrect information

### ISSUE THREAD

**Issue by hannob** [s9y/s9y.github.io#93]
In the PR about the PHP version I noted this sentence:
"Serendipity is fully PHP 8.x compatible and encourages the use of PHP bytecode compilers like APC, Zend Cache or ionCube."

I think the part about bytecode compilers is wrong and obsolete in multiple ways:
* APC has not seen any development since 2012 and is considered obsolete.
* Zend Cache is as far as I understand not a bytecode compiler, but a cache for PHP objects. It is also obsolete. This likely meant Zend OPcache, which was later merged into PHP core (and was also the point when APC became obsolete) and is now only called OPcache.
* I don't think ionCube is a cache at all (the webpage does not say anything about caching). It is a proprietary PHP code obfuscator. It's probably not something s9y should endorse and also likely not very useful for running foss code.

So probably this should just be:
"Serendipity is fully PHP 8.x compatible and encourages the use of PHP bytecode compilers OPcache."

**Comment by fe-hicking** [comment]
👍 Totally agreed!
I'll merge that if there are no objections @onli ?

**Comment by onli** [comment]
That'd be great @fe-hicking :)

**Comment by garvinhicking** [comment]
Committed, thanks! :-)
